name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  macOS_test:
    name: Test on macOS ${{ matrix.macOS_version }}
    
    runs-on: macos-${{ matrix.macOS_version }}
    
    strategy:
      matrix:
        macOS_version: [ 10.14, 10.15 ]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build & Test Interval Configured for Release
        run: swift test --configuration release --enable-code-coverage --enable-test-discovery --list-tests --sanitize=thread --show-codecov-path
      - name: Build & Test Interval Configured for Debug
        if: ${{ failure() }}
        run: swift test --configuration debug --enable-code-coverage --enable-test-discovery --list-tests --sanitize=thread --show-codecov-path --verbose
  
  ubuntu_test:
    name: Test on Ubuntu ${{ matrix.ubuntu_version }} with Swift ${{ matrix.swift_version }}
    
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    
    container: 
      image: swift:${{ matrix.swift_version }}
    
    strategy:
      matrix:
        ubuntu_version: [ 16.04, 18.04, 20.04 ]
        swift_version: [ 5.2 ]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build & Test Interval Configured for Release
        run: swift test --configuration release --enable-code-coverage --enable-test-discovery --list-tests --sanitize=thread
      - name: Build & Test Interval Configured for Debug
        if: ${{ failure() }}
        run: swift test --configuration debug --enable-code-coverage --enable-test-discovery --list-tests --sanitize=thread --verbose
       
