name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  macOS_test:
    name: Test on macOS ${{ matrix.macOS_version }}
    
    runs-on: macos-${{ matrix.macOS_version }}
    
    strategy:
      matrix:
        macOS_version: [ 10.14, 10.15 ]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Cache Dependencies and Build Outputs
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Print Package Description
        run: swift package describe
      - name: Build & Test Interval
        run: swift test --enable-code-coverage --sanitize=thread
      - name: Report Code Coverage
        uses: maxep/spm-lcov-action@0.3.1
      - name: Get Code Coverage path
        if: ${{ always() }}
        id: showCodeCoveragePath
        run: echo "::set-output name=codeCoveragePath::$(swift test --show-codecov-path)"
      - name: Upload Code Coverage Reports to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ steps.showCodeCoveragePath.outputs.codeCoveragePath}}
  
  ubuntu_test:
    name: Test on Ubuntu ${{ matrix.ubuntu_version }} with Swift ${{ matrix.swift_version }}
    
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    
    container: 
      image: swift:${{ matrix.swift_version }}
    
    strategy:
      matrix:
        ubuntu_version: [ 16.04, 18.04, 20.04 ]
        swift_version: [ 5.2 ]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Cache Dependencies and Build Outputs
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Print Package Description
        run: swift package describe
      - name: Build & Test Interval
        run: swift test --enable-code-coverage --enable-test-discovery --sanitize=thread
      - name: Report Code Coverage
        uses: maxep/spm-lcov-action@0.3.1
      - name: Get Code Coverage path
        if: ${{ always() }}
        id: showCodeCoveragePath
        run: echo "::set-output name=codeCoveragePath::$(swift test --show-codecov-path)"
      - name: Upload Code Coverage Reports to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ steps.showCodeCoveragePath.outputs.codeCoveragePath}}
       
